apiVersion: v1
kind: Service
metadata:
  name: http-status-code-service
spec:
  ports:
  - port: 80
    targetPort: 5000
    name: http
  selector:
    app: http-status-code
  type: ClusterIP
  clusterIP: 10.0.0.214
status:
   loadBalancer: {}