apiVersion: v1
kind: Service
metadata:
  name: useragent-service
spec:
  ports:
  - port: 80
    targetPort: 5000
    name: http
  selector:
    app: useragent
  type: ClusterIP
status:
   loadBalancer: {}