apiVersion: v1
kind: Service
metadata:
  name: myip-service
spec:
  ports:
  - port: 80
    targetPort: 5000
    name: http
  selector:
    app: myip
  type: ClusterIP
  clusterIP: 10.0.0.24
status:
   loadBalancer: {}
